# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: openjdk:8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  ## Set timezone, default gitlab/docker can cause problem with DB
  - TZ=Europe/London
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  ## SSH config
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - ./gradlew build -x test --info --stacktrace
  cache:
    key: "$CI_COMMIT_REF_NAME"  
    paths:
      - ./build
      - ./.gradle

test:
  stage: test
  script:
    - ./gradlew test --info --stacktrace
  artifacts:
    reports:
      junit: "**/build/test-results/test/TEST-*.xml"
  cache:
    key: "$CI_COMMIT_REF_NAME"   
    paths:
      - ./build
      - ./.gradle

publish:
  stage: publish
  script:
    - ./gradlew publish --info --stacktrace
  cache:
    key: "$CI_COMMIT_REF_NAME"  
    paths:
      - ./build
      - ./.gradle
  only:
    - tags